abs_action: false
mode: train  # train or inference
obs_keys: ['poly_coef', 'start_conf', 'goal_conf']
dataset_name: franka_ruckig_100hz_polynomial.zarr
action_dim: 9
obs_dim: 14
obs_steps: 1
action_steps: 64
use_group_norm: true
use_seq: true

# training settings
device: cuda:0
seed: 0
gradient_steps: 100000
batch_size: 64
horizon: 7
nn: chi_unet
diffusion: ddpm
diffusion_steps: 25
condition: identity  # identity, None
normalize: False

# optimizer
lr: 0.0001
dim_mult: [1, 4, 2]
model_dim: 32

predict_noise: True
ema_rate: 0.9999
sample_steps: 25
action_loss_weight: 1.0
val_freq: 1000

# log and inference
log_freq: 100
save_freq: 5000
inference_solver: ddpm
inference_steps: 10000
visualization: True

episode_num: 1
max_pos_err: 0.05
max_rot_err: 0.1
max_iter: 10000
# json_file: '500_fixed_goal_results_pos001.json'
