#!/usr/bin/env python3
"""
Visualize whether candidate joint configurations under the same task condition
show a manifold gap in forward travel ability.

Input:
- One task condition `(pos, direction, normal)`, selected from the batched
  ranking log by `--case-idx`.
- Candidate configurations are generated by the same functions used in
  `lnet_contrastive_fr3_rotation_cone_eval.py`.

What this script does:
- Collects many feasible candidate joint angles under the same position and
  rotation-cone constraint.
- Rolls out each candidate with the same tracker and measures its real travel
  length.
- Projects the candidates into 2D with PCA in two ways:
  1. raw joint-angle PCA,
  2. local task-nullspace PCA around a reference candidate.
- Colors all points by real rollout length.
- Saves plots and a summary JSON for checking whether high-capability samples
  form a separated manifold/submanifold.

Outputs:
- `pca_q_raw.png`
- `pca_q_nullspace.png`
- `scatter_len_vs_anchor_dist.png`
- `summary.json`
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import torch


CURRENT_DIR = Path(__file__).resolve().parent
ROOT_DIR = CURRENT_DIR.parent
LENGTH_PREDICTION_DIR = ROOT_DIR / "length_prediction"
TRAJ_DIR = ROOT_DIR / "trajectory_generation"

if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))
if str(LENGTH_PREDICTION_DIR) not in sys.path:
    sys.path.insert(0, str(LENGTH_PREDICTION_DIR))
if str(TRAJ_DIR) not in sys.path:
    sys.path.insert(0, str(TRAJ_DIR))

from length_prediction.lnet_contrastive_fr3_rotation_cone_eval import build_tracker, collect_candidate_qs, rollout_same_task
from length_prediction.lnet_contrastive_fr3_rotation_cone_eval_batch_analysis import DEFAULT_INPUT, parse_log
from fr3_nullspace_straight import position_jacobian_batch


DEFAULT_OUTDIR = CURRENT_DIR / "outputs" / "nullspace_manifold_gap"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Visualize manifold gap of same-task nullspace candidates.")
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--outdir", type=Path, default=DEFAULT_OUTDIR)
    parser.add_argument("--case-idx", type=int, default=151)
    parser.add_argument("--device", type=str, default="cuda" if torch.cuda.is_available() else "cpu")
    parser.add_argument("--num-candidates", type=int, default=256)
    parser.add_argument("--oversample", type=int, default=2048)
    parser.add_argument("--pos-tol-mm", type=float, default=2.0)
    parser.add_argument("--correction-iters", type=int, default=50)
    parser.add_argument("--correction-tol", type=float, default=1e-4)
    parser.add_argument("--correction-damping", type=float, default=1e-3)
    parser.add_argument("--reference", choices=["best", "median", "worst"], default="best")
    return parser.parse_args()


def pca_2d(x: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    x = np.asarray(x, dtype=np.float64)
    mean = x.mean(axis=0, keepdims=True)
    xc = x - mean
    _, _, vt = np.linalg.svd(xc, full_matrices=False)
    basis = vt[:2].T
    proj = xc @ basis
    return proj.astype(np.float32), mean.reshape(-1).astype(np.float32), basis.astype(np.float32)


def find_task_row(rows: list[dict], case_idx: int) -> dict:
    rows = [row for row in rows if "pos" in row and "direction" in row and "normal" in row]
    for row in rows:
        if int(row["case_idx"]) == int(case_idx):
            return row
    raise ValueError(f"case_idx={case_idx} not found in log: {case_idx}")


def build_local_nullspace_basis(tracker, tracker_device: torch.device, q_ref_np: np.ndarray) -> np.ndarray:
    q_ref = torch.from_numpy(q_ref_np[None, :].astype(np.float32)).to(tracker_device)
    j_pos, _ = position_jacobian_batch(tracker.robot, q_ref, create_graph=False)
    j_pos_np = j_pos[0].detach().cpu().numpy().astype(np.float64)
    _, _, vt = np.linalg.svd(j_pos_np, full_matrices=True)
    rank = int(np.linalg.matrix_rank(j_pos_np))
    null_basis = vt[rank:].T
    return null_basis.astype(np.float32)


def main() -> None:
    args = parse_args()
    args.outdir.mkdir(parents=True, exist_ok=True)

    rows = parse_log(args.input)
    row = find_task_row(rows, int(args.case_idx))

    pos = np.asarray(row["pos"], dtype=np.float32)
    direction = np.asarray(row["direction"], dtype=np.float32)
    normal = np.asarray(row["normal"], dtype=np.float32)

    device = torch.device(args.device)
    tracker, tracker_device = build_tracker(device)

    q_batch_np, raw_err_np = collect_candidate_qs(
        tracker,
        tracker_device,
        pos,
        direction,
        normal,
        int(args.num_candidates),
        int(args.oversample),
        float(args.pos_tol_mm),
        int(args.correction_iters),
        float(args.correction_tol),
        float(args.correction_damping),
    )
    real_len_np = rollout_same_task(tracker, tracker_device, q_batch_np, direction, normal)

    order = np.argsort(real_len_np)
    if args.reference == "best":
        ref_idx = int(order[-1])
    elif args.reference == "worst":
        ref_idx = int(order[0])
    else:
        ref_idx = int(order[len(order) // 2])

    q_ref_np = q_batch_np[ref_idx]
    q_delta_np = q_batch_np - q_ref_np[None, :]
    anchor_dist_np = np.linalg.norm(q_delta_np, axis=1).astype(np.float32)

    raw_proj_np, raw_mean_np, raw_basis_np = pca_2d(q_batch_np)

    null_basis_np = build_local_nullspace_basis(tracker, tracker_device, q_ref_np)
    if null_basis_np.shape[1] >= 2:
        null_coords_np = q_delta_np @ null_basis_np
        null_proj_np, null_mean_np, null_pca_basis_np = pca_2d(null_coords_np)
    elif null_basis_np.shape[1] == 1:
        null_coords_np = q_delta_np @ null_basis_np
        null_proj_np = np.concatenate([null_coords_np, np.zeros_like(null_coords_np)], axis=1).astype(np.float32)
        null_mean_np = np.zeros(1, dtype=np.float32)
        null_pca_basis_np = np.ones((1, 1), dtype=np.float32)
    else:
        null_coords_np = np.zeros((q_batch_np.shape[0], 1), dtype=np.float32)
        null_proj_np = np.zeros((q_batch_np.shape[0], 2), dtype=np.float32)
        null_mean_np = np.zeros(1, dtype=np.float32)
        null_pca_basis_np = np.zeros((1, 1), dtype=np.float32)

    high_mask = real_len_np >= np.percentile(real_len_np, 80)
    low_mask = real_len_np <= np.percentile(real_len_np, 20)

    vmin = float(real_len_np.min())
    vmax = float(real_len_np.max())

    fig, ax = plt.subplots(figsize=(8, 6), dpi=220)
    sc = ax.scatter(raw_proj_np[:, 0], raw_proj_np[:, 1], c=real_len_np, s=24, cmap="viridis", vmin=vmin, vmax=vmax)
    ax.scatter(raw_proj_np[high_mask, 0], raw_proj_np[high_mask, 1], facecolors="none", edgecolors="red", s=40, linewidths=1.5)
    ax.scatter(raw_proj_np[low_mask, 0], raw_proj_np[low_mask, 1], facecolors="none", edgecolors="white", s=40, linewidths=1.2)
    ax.scatter(raw_proj_np[ref_idx, 0], raw_proj_np[ref_idx, 1], marker="x", color="black", s=60, linewidths=2.0)
    ax.set_title("Raw Joint PCA")
    ax.set_xlabel("PC1")
    ax.set_ylabel("PC2")
    ax.grid(alpha=0.2)
    fig.colorbar(sc, ax=ax, label="real rollout length")
    fig.tight_layout()
    fig.savefig(args.outdir / "pca_q_raw.png")
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(8, 6), dpi=220)
    sc = ax.scatter(null_proj_np[:, 0], null_proj_np[:, 1], c=real_len_np, s=24, cmap="viridis", vmin=vmin, vmax=vmax)
    ax.scatter(null_proj_np[high_mask, 0], null_proj_np[high_mask, 1], facecolors="none", edgecolors="red", s=40, linewidths=1.5)
    ax.scatter(null_proj_np[low_mask, 0], null_proj_np[low_mask, 1], facecolors="none", edgecolors="white", s=40, linewidths=1.2)
    ax.scatter(null_proj_np[ref_idx, 0], null_proj_np[ref_idx, 1], marker="x", color="black", s=60, linewidths=2.0)
    ax.set_title("Local Task-Nullspace PCA")
    ax.set_xlabel("PC1")
    ax.set_ylabel("PC2")
    ax.grid(alpha=0.2)
    fig.colorbar(sc, ax=ax, label="real rollout length")
    fig.tight_layout()
    fig.savefig(args.outdir / "pca_q_nullspace.png")
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(8, 6), dpi=220)
    sc = ax.scatter(anchor_dist_np, real_len_np, c=real_len_np, s=24, cmap="viridis", vmin=vmin, vmax=vmax)
    ax.set_title("Travel Ability vs Distance to Reference")
    ax.set_xlabel("joint distance to reference")
    ax.set_ylabel("real rollout length")
    ax.grid(alpha=0.2)
    fig.colorbar(sc, ax=ax, label="real rollout length")
    fig.tight_layout()
    fig.savefig(args.outdir / "scatter_len_vs_anchor_dist.png")
    plt.close(fig)

    summary = {
        "case_idx": int(args.case_idx),
        "task": {
            "pos": pos.tolist(),
            "direction": direction.tolist(),
            "normal": normal.tolist(),
        },
        "num_candidates": int(q_batch_np.shape[0]),
        "reference_mode": args.reference,
        "reference_idx": int(ref_idx),
        "reference_real_len": float(real_len_np[ref_idx]),
        "real_len": {
            "min": float(real_len_np.min()),
            "max": float(real_len_np.max()),
            "mean": float(real_len_np.mean()),
            "std": float(real_len_np.std()),
            "p20": float(np.percentile(real_len_np, 20)),
            "p80": float(np.percentile(real_len_np, 80)),
        },
        "anchor_distance": {
            "min": float(anchor_dist_np.min()),
            "max": float(anchor_dist_np.max()),
            "mean": float(anchor_dist_np.mean()),
            "std": float(anchor_dist_np.std()),
        },
        "nullspace_dimension": int(null_basis_np.shape[1]),
        "raw_err_mm": {
            "mean": float(raw_err_np.mean() * 1000.0),
            "max": float(raw_err_np.max() * 1000.0),
        },
        "saved_files": [
            "pca_q_raw.png",
            "pca_q_nullspace.png",
            "scatter_len_vs_anchor_dist.png",
        ],
    }
    (args.outdir / "summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")
    print(json.dumps(summary, indent=2))
    print(f"[saved] {args.outdir}")


if __name__ == "__main__":
    main()
