traj_num: 1000
abs_action: false
mode: train  # train or inference
obs_keys: ['interp_confs', 'interp_spds']
action_dim: 12
obs_dim: 12
obs_steps: 1
action_steps: 32
use_group_norm: true
use_seq: true

# training settings
device: cuda:0
seed: 0
gradient_steps: 1000000
batch_size: 64
horizon: 33
nn: chi_unet
diffusion: ddpm
sample_steps: 20
# optimizer
lr: 0.0001

# log
log_freq: 100
save_freq: 2000