traj_num: 1000
abs_action: false
mode: inference  # train or inference
obs_keys: ['interp_confs', 'interp_spds']
action_dim: 12
obs_dim: 6
obs_steps: 2
action_steps: 32
use_group_norm: true
use_seq: true

# training settings
device: cuda:0
seed: 0
gradient_steps: 10000000
batch_size: 64
horizon: 33
nn: chi_unet
diffusion: ddpm
sample_steps: 20
# optimizer
lr: 0.0001
dim_mult: [1, 4, 2]
model_dim: 32

predict_noise: True
ema_rate: 0.9999
diffusion_steps: 25
action_loss_weight: 1.0
val_freq: 20000

# log and inference
log_freq: 100
save_freq: 5000
inference_solver: ddpm
inference_samples: 100
normalize: False
