abs_action: false
mode: train  # train or inference
obs_keys: ['jnt_pos', 'jnt_vel', 'jnt_acc', 'goal_conf']
dataset_name: franka_ruckig.zarr
action_dim: 7
obs_dim: 14
obs_steps: 1
action_steps: 64
use_group_norm: true
use_seq: true

# training settings
device: cuda:0
seed: 0
gradient_steps: 10000000
batch_size: 64
horizon: 128
nn: chi_unet
diffusion: ddpm
sample_steps: 20
# optimizer
lr: 0.0001
dim_mult: [1, 4, 2]
model_dim: 32

predict_noise: True
ema_rate: 0.9999
diffusion_steps: 25
action_loss_weight: 1.0
val_freq: 1000

# log and inference
log_freq: 100
save_freq: 1000
inference_solver: ddpm
inference_steps: 10000
normalize: False
visualization: True

episode_num: 1
max_pos_err: 0.05
max_rot_err: 0.1
max_iter: 10000
